# Generated by Django 6.0 on 2026-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('genres', models.CharField(choices=[('action', 'Боевик'), ('comedy', 'Комедия'), ('drama', 'Драма'), ('horror', 'Ужасы'), ('fantasy', 'Фэнтези'), ('sci-fi', 'Фантастика'), ('other', 'Другое')], max_length=30, verbose_name='Жанр')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='movies', to='cineboard.tag')),
            ],
        ),
    ]
