# Generated by Django 6.0 on 2026-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Напишите, что вы ищете ?')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_delivery', models.CharField(choices=[('🚚', '🚚'), ('🏪', '🏪')], max_length=100, verbose_name='Как вы бы хотели получить товар?')),
            ],
        ),
    ]
