# Generated by Django 6.0 on 2025-12-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('type_products', models.CharField(choices=[('bakery products', 'Bakery products'), ('grains and pasta', 'Grains and pasta'), ('meat products', 'Meat products'), ('dairy products', 'Dairy products'), ('vegetables', 'Vegetables')], max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
