# Generated by Django 6.0 on 2026-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='reviews',
            name='is_recommended',
            field=models.BooleanField(default=True, verbose_name='Рекомендует продукт'),
        ),
    ]
