# Generated by Django 6.0 on 2026-01-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_create_at_products_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='choice_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.products'),
        ),
    ]
